# Generated by Django 4.1.5 on 2023-01-25 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="gender",
            field=models.CharField(
                choices=[("MAN", "Man"), ("WOMAN", "Wom")], default="MAN", max_length=9
            ),
        ),
    ]
