# Generated by Django 4.1.5 on 2023-01-25 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0004_alter_post_gender"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="image",
            field=models.ImageField(default=" ", upload_to="posts/"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="post",
            name="gender",
            field=models.CharField(
                choices=[("MAN", "Man"), ("WOMAN", "Wom")],
                default="MAN",
                max_length=999999999999999,
            ),
        ),
    ]
