# Generated by Django 4.1.5 on 2023-01-25 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0007_post_author_alter_post_gender"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="content",
            field=models.TextField(max_length=100000),
        ),
        migrations.AlterField(
            model_name="post",
            name="gender",
            field=models.CharField(
                choices=[("MAN", "Man"), ("WOMAN", "Woman")],
                default="MAN",
                max_length=999999999999999,
            ),
        ),
    ]
